### ISSUE TITLE
setUnlocalizedName should be changed to setBlockName

### ISSUE THREAD

**Issue by elifoster** [soultek101/projectzulu1.7.10#22]
This is causing a crash because the setUnlocalizedName method no longer exists.

**Comment by soultek101** [comment]
Noted. BTW can you send me the crash log so that I can check for possibly other related issues. thank you.

**Comment by elifoster** [comment]
There aren't any other related issues in that particular crash, since it crashes from the first ItemBlockDeclaration.

**Comment by elifoster** [comment]
It appears that you had already fixed this at some point, it's just not in release versions.
